apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: k8s-learn-ns
spec:
  type: NodePort          # Exposes the service on a port on each node (Minikube VM)
  selector:
    app: web-app          # Traffic sent to this Service goes to Pods with this label
  ports:
  - protocol: TCP
    port: 80              # The port the Service listens on internally
    targetPort: 80        # The port the Container is listening on
    nodePort: 30007       # The static port accessible from your laptop (30000-32767)