apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: k8s-learn-ns
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body style="background-color: #0984e3; color: white; text-align: center; padding-top: 50px;">
        <h1>This site is powered by ConfigMaps!</h1>
        <p>No Docker build required for this update.</p>
    </body>
    </html>